### PR TITLE
Changes added

### PR DESCRIPTION
**Pull request by zidailiu**
loading fixed

### CODE REVIEW

**Comment by ikaier** [comment]
Fix the conflict!!!!!!

**Comment by zidailiu** [comment]
I have fixed the conflicts, please kindly review my changes. I have put my heart into working this. Thank you from the bottom of my heart!

**Comment by ikaier** [comment]
lgtm

**Comment by ikaier** [comment]
nice job John, you will become our new senior developer in next 50 years I promise.

**Comment by zidailiu** [comment]
gan

**Pull request merged**
